name: "P6 GHA: Deploys a CDK Application to AWS"
description: "P6 GHA: Deploys a CDK Application to AWS"
author: "Philip M. Gollucci"
inputs:
  aws_region:
    description: "AWS region for deployment"
    required: false
    default: "us-east-1"
  aws_role:
    description: "AWS role to assume"
    required: true
  aws_session_name:
    description: "Session name for the AWS role"
    required: true
  cdk_deploy_account:
    description: "AWS CDK deploy account"
    required: true
  cdk_deploy_region:
    description: "AWS CDK deploy region"
    required: true
  p6_custom_build_cmd:
    description: "Custom build command to run"
    required: false
    default: "pnpm run deploy --all --require-approval never"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Checkout code p6common
      uses: actions/checkout@v4.2.2
      with:
        repository: "p6m7g8-dotfiles/p6common"
        path: ".deps/p6common"
    - name: Checkout code p6aws
      uses: actions/checkout@v4.2.2
      with:
        repository: "p6m7g8-dotfiles/p6aws"
        path: ".deps/p6aws"
    - name: Debug
      shell: bash
      run: |
        pwd
        ls -alF
    - name: Install Node.js
      shell: bash
      run: |
        curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node-v22.11.0-linux-x64.tar.xz
        sudo tar -xJf node-v22.11.0-linux-x64.tar.xz -C /usr/local
        echo "/usr/local/node-v22.11.0-linux-x64/bin" >> $GITHUB_PATH
    - name: Corepack
      shell: bash
      run: |
        sudo corepack enable
        sudo corepack prepare pnpm@latest --activate
    - name: Restore NPM node_modules cache
      uses: actions/cache/restore@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node_modules-
    - name: Install pnpm and dependencies
      shell: bash
      run: pnpm install
    - name: Cache NPM dependencies
      uses: actions/cache@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node_modules-
    - name: Assume role using OIDC
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name: ${{ inputs.aws_session_name }}
    - name: Make ~/.aws
      shell: bash
      run: mkdir -p ~/.aws
    - name: Run deploy
      shell: bash
      env:
        CDK_DEPLOY_ACCOUNT: ${{ inputs.cdk_deploy_account }}
        CDK_DEPLOY_REGION: ${{ inputs.cdk_deploy_region }}
        CDK_DEFAULT_ACCOUNT: ${{ inputs.cdk_deploy_account }}
        CDK_DEFAULT_REGION: ${{ inputs.cdk_deploy_region }}
        AWS_REGION: ${{ inputs.aws_region }}
        P6_DFZ_SRC_P6M7G8_DOTFILES_DIR: ".deps"
      run: ${{ inputs.p6_custom_build_cmd }}
